### ISSUE TITLE
errors when running "make test"

### ISSUE THREAD

**Issue by hainguyenct** [mmp2/megaman#82]
Dear all,
I installed megaman, and it can be appeared by "conda list"
megaman                   0.3.dev0                  <pip>
megaman                   0.2                 np111py27_1    conda-forge

However, I use "make test" to check, the error as below displayed:
Anyone could help me? Thank you.
```
make test
mkdir -p /tmp/megaman
python setup.py install
Cythonizing sources
megaman/__check_build/_check_build.pyx has not changed
megaman/geometry/cyflann/index.pyx has not changed
Compiling FLANN with FLANN_ROOT=/anaconda2
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "megaman.__check_build._check_build" sources
building extension "megaman.geometry/cyflann.index" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
running install_lib
running install_data
running install_egg_info
Removing /anaconda2/lib/python2.7/site-packages/megaman-0.3.dev0-py2.7.egg-info
Writing /anaconda2/lib/python2.7/site-packages/megaman-0.3.dev0-py2.7.egg-info
running install_clib
customize UnixCCompiler
cd /tmp/megaman && nosetests megaman
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
EEEEEEE.E........
======================================================================
ERROR: Failure: ImportError (numpy.core.multiarray failed to import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/datasets/__init__.py", line 1, in <module>
    from .datasets import (get_megaman_image, generate_megaman_data,
  File "/anaconda2/lib/python2.7/site-packages/megaman/datasets/datasets.py", line 8, in <module>
    from sklearn.utils import check_random_state
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/base.py", line 12, in <module>
    from .utils.fixes import signature
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
ImportError: numpy.core.multiarray failed to import

======================================================================
ERROR: Failure: ImportError (cannot import name __check_build)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/embedding/__init__.py", line 7, in <module>
    from .locally_linear import LocallyLinearEmbedding
  File "/anaconda2/lib/python2.7/site-packages/megaman/embedding/locally_linear.py", line 17, in <module>
    from ..embedding.base import BaseEmbedding
  File "/anaconda2/lib/python2.7/site-packages/megaman/embedding/base.py", line 9, in <module>
    from sklearn.base import BaseEstimator, TransformerMixin
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build

======================================================================
ERROR: Failure: ImportError (cannot import name __check_build)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/__init__.py", line 4, in <module>
    from .geometry import Geometry
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/geometry.py", line 36, in <module>
    from .adjacency import compute_adjacency_matrix
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/adjacency.py", line 4, in <module>
    from sklearn import neighbors
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build

======================================================================
ERROR: Failure: ImportError (cannot import name __check_build)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/relaxation/__init__.py", line 3, in <module>
    from .riemannian_relaxation import *
  File "/anaconda2/lib/python2.7/site-packages/megaman/relaxation/riemannian_relaxation.py", line 9, in <module>
    from megaman.geometry import RiemannMetric
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/__init__.py", line 4, in <module>
    from .geometry import Geometry
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/geometry.py", line 36, in <module>
    from .adjacency import compute_adjacency_matrix
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/adjacency.py", line 4, in <module>
    from sklearn import neighbors
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build

======================================================================
ERROR: Failure: ImportError (cannot import name __check_build)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/utils/tests/test_analyze_dimension_and_radius.py", line 4, in <module>
    import megaman.utils.analyze_dimension_and_radius as adar
  File "/anaconda2/lib/python2.7/site-packages/megaman/utils/analyze_dimension_and_radius.py", line 16, in <module>
    from megaman.geometry.adjacency import compute_adjacency_matrix
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/__init__.py", line 4, in <module>
    from .geometry import Geometry
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/geometry.py", line 36, in <module>
    from .adjacency import compute_adjacency_matrix
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/adjacency.py", line 4, in <module>
    from sklearn import neighbors
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build

======================================================================
ERROR: Failure: ImportError (cannot import name __check_build)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/utils/tests/test_eigendecomp.py", line 3, in <module>
    from megaman.utils.eigendecomp import (eigen_decomposition, null_space,
  File "/anaconda2/lib/python2.7/site-packages/megaman/utils/eigendecomp.py", line 8, in <module>
    from sklearn.utils.validation import check_random_state
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build

======================================================================
ERROR: Failure: ImportError (cannot import name __check_build)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/utils/tests/test_estimate_radius.py", line 4, in <module>
    from megaman.utils.estimate_radius import run_estimate_radius
  File "/anaconda2/lib/python2.7/site-packages/megaman/utils/estimate_radius.py", line 3, in <module>
    from megaman.geometry.rmetric import riemann_metric_lazy
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/__init__.py", line 4, in <module>
    from .geometry import Geometry
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/geometry.py", line 36, in <module>
    from .adjacency import compute_adjacency_matrix
  File "/anaconda2/lib/python2.7/site-packages/megaman/geometry/adjacency.py", line 4, in <module>
    from sklearn import neighbors
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build

======================================================================
ERROR: Failure: ImportError (cannot import name __check_build)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda2/lib/python2.7/site-packages/megaman/utils/tests/test_spectral_clustering.py", line 1, in <module>
    from sklearn import neighbors
  File "/Users/hainguyen/.local/lib/python2.7/site-packages/sklearn/__init__.py", line 56, in <module>
    from . import __check_build
ImportError: cannot import name __check_build

----------------------------------------------------------------------
Ran 17 tests in 0.084s

FAILED (errors=8)
make: *** [test] Error 1
```

**Comment by yuchaz** [comment]
From the error you provided, seems like it's the compatibility issue of numpy. Can you try to update your numpy version?

**Comment by hainguyenct** [comment]
I tried with "pip install numpy -I", and it worked!
