### ISSUE TITLE
Make test failed with ERROR: Failure: ImportError (No module named _check_build

### ISSUE THREAD

**Issue by ffancheng** [mmp2/megaman#99]
(manifold_env) /tmp/megaman(master) $make test
mkdir -p /tmp/megaman
python setup.py install
Cythonizing sources
megaman/__check_build/_check_build.pyx has not changed
megaman/geometry/cyflann/index.pyx has not changed
Compiling FLANN with FLANN_ROOT=/Users/fche0019/miniconda3/envs/manifold_env
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "megaman.__check_build._check_build" sources
building extension "megaman.geometry/cyflann.index" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
running install_lib
running install_data
running install_egg_info
Removing /Users/fche0019/miniconda3/envs/manifold_env/lib/python2.7/site-packages/megaman-0.3.dev0-py2.7.egg-info
Writing /Users/fche0019/miniconda3/envs/manifold_env/lib/python2.7/site-packages/megaman-0.3.dev0-py2.7.egg-info
running install_clib
customize UnixCCompiler
cd /tmp/megaman && nosetests megaman
E
======================================================================
ERROR: Failure: ImportError (No module named _check_build
___________________________________________________________________________
Contents of /private/tmp/megaman/megaman/__check_build:
__init__.py               setup.pyc                 _check_build.c
setup.py                  __init__.pyc              _check_build.pyx
___________________________________________________________________________
It seems that megaman has not been built correctly.

If you have installed megaman from source, please do not forget
to build the package before using it: run `python setup.py install`
in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/private/tmp/megaman/megaman/__init__.py", line 7, in <module>
    from . import __check_build
  File "/private/tmp/megaman/megaman/__check_build/__init__.py", line 56, in <module>
    raise_build_error(e)
  File "/private/tmp/megaman/megaman/__check_build/__init__.py", line 51, in raise_build_error
    msg=msg))
ImportError: No module named _check_build
___________________________________________________________________________
Contents of /private/tmp/megaman/megaman/__check_build:
__init__.py               setup.pyc                 _check_build.c
setup.py                  __init__.pyc              _check_build.pyx
___________________________________________________________________________
It seems that megaman has not been built correctly.

If you have installed megaman from source, please do not forget
to build the package before using it: run `python setup.py install`
in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
make: *** [test] Error 1

**Comment by ffancheng** [comment]
Please find below the `make test` output for Python 3.5.

(manifold_env)  /tmp/megaman   master  make test
mkdir -p /tmp/megaman
python setup.py install
Cythonizing sources
megaman/__check_build/_check_build.pyx has not changed
megaman/geometry/cyflann/index.pyx has not changed
Compiling FLANN with FLANN_ROOT=/Users/fche0019/miniconda3/envs/manifold_env
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "megaman.__check_build._check_build" sources
building extension "megaman.geometry/cyflann.index" sources
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
#### ['/usr/bin/clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-I/Users/fche0019/miniconda3/envs/manifold_env/include', '-arch', 'x86_64', '-I/Users/fche0019/miniconda3/envs/manifold_env/include', '-arch', 'x86_64', '-I/usr/local/opt/zlib/include', '-I/usr/local/opt/bzip2/include'] #######
customize UnixCCompiler using build_ext
running install_lib
running install_data
running install_egg_info
Removing /Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/site-packages/megaman-0.3.dev0-py3.5.egg-info
Writing /Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/site-packages/megaman-0.3.dev0-py3.5.egg-info
running install_clib
customize UnixCCompiler
cd /tmp/megaman && nosetests megaman
E
___________________________________________________________________________
ERROR: Failure: ImportError (No module named 'megaman.__check_build._check_build'
___________________________________________________________________________
Contents of /private/tmp/megaman/megaman/__check_build:
__init__.py               __pycache__               setup.pyc
_check_build.c            setup.py                  __init__.pyc
_check_build.pyx
___________________________________________________________________________
It seems that megaman has not been built correctly.

If you have installed megaman from source, please do not forget
to build the package before using it: run `python setup.py install`
in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/megaman/megaman/__check_build/__init__.py", line 54, in <module>
    from ._check_build import check_build
ImportError: No module named 'megaman.__check_build._check_build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Users/fche0019/miniconda3/envs/manifold_env/lib/python3.5/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/private/tmp/megaman/megaman/__init__.py", line 7, in <module>
    from . import __check_build
  File "/private/tmp/megaman/megaman/__check_build/__init__.py", line 56, in <module>
    raise_build_error(e)
  File "/private/tmp/megaman/megaman/__check_build/__init__.py", line 51, in raise_build_error
    msg=msg))
ImportError: No module named 'megaman.__check_build._check_build'
___________________________________________________________________________
Contents of /private/tmp/megaman/megaman/__check_build:
__init__.py               __pycache__               setup.pyc
_check_build.c            setup.py                  __init__.pyc
_check_build.pyx
___________________________________________________________________________
It seems that megaman has not been built correctly.

If you have installed megaman from source, please do not forget
to build the package before using it: run `python setup.py install`
in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
make: *** [test] Error 1

**Comment by ffancheng** [comment]
@jmcq89 @mmp2
